name: ğŸš€ Feature request
description: Add contributors to guestbook ğŸ’¡
title: "Feature:"
labels: [ğŸ’¡ feature]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: dropdown
    attributes:
      multiple: false
      label: Type of feature
      description: Select the type of feature request, the lowercase should also be the PR prefix.
      options:
        - "ğŸ• Feature"
        - "ğŸ› Fix"
        - "ğŸ“ Documentation"
        - "ğŸ¨ Style"
        - "ğŸ§‘â€ğŸ’» Refactor"
        - "ğŸ”¥ Performance"
        - "âœ… Test"
        - "ğŸ¤– Build"
        - "ğŸ” CI"
        - "ğŸ“¦ Chore"
        - "â© Revert"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: Please describe the issue â€” for example, "As part of the Intro to Open Source course, we are encouraged to contribute to this repo.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suggested solution
      description: Suggest a solution â€” for example, "Add myself as a contributor."
  - type: input
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem or helpful links here.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://docs.opensauced.pizza/contributing/code-of-conduct/)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: checkboxes
    id: contribution
    attributes:
      label: Getting Started Instructions
      description: Please read [Getting Started](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=getting-started) to add yourself as a contributor.
      options:
        - label: I agree to follow this project's Getting Started instructions
          required: true
